export const projects = [
	{
	  id: "1",
	  date: "2023",
	  route: "https://innovacioneducativa.upm.es/mooc/informacion-mooc?idmooc=356",
	  title: "Utilización de escape rooms y videojuegos educativos en la Educación Universitaria",
	  center: "E.T.S DE ING. DE SISTEMAS INFORMÁTICOS",
	  description: "",
	  tags: "Aprendizaje Activo,Aprendizaje Autónomo,Investigación educativa,Aula Invertida,Gamificación",
	  category: "erg",
	},
	{
	  id: "2",
	  date: "2023",
	  route: "http://ging.github.io/ediphy/",
	  title: "Ediphy",
	  center: "E.T.S DE ING. DE SISTEMAS INFORMÁTICOS",
	  description: "",
	  tags: "Aprendizaje Activo, Aprendizaje Autónomo,Investigación educativa, Aula Invertida, Gamificación",
	  category: "ind",
	},
	{
	  id:"3",
	  date: "2023",
	  route: "https://innovacioneducativa.upm.es/mooc/informacion-mooc?idmooc=356",
	  title: "Utilización de escape rooms y videojuegos educativos en la Educación Universitaria",
	  center: "E.T.S DE ING. DE SISTEMAS INFORMÁTICOS",
	  description: "",
	  tags: "Aprendizaje Activo,Aprendizaje Autónomo,Investigación educativa, Aula Invertida,Gamificación",
	  category: "other",
	},
	{
	  id:"4",
	  date: "2023",
	  route: "https://innovacioneducativa.upm.es/mooc/informacion-mooc?idmooc=356",
	  title: "Utilización de escape rooms",
	  center: "E.T.S DE ING. DE SISTEMAS INFORMÁTICOS",
	  description: "",
	  tags: "Aprendizaje Activo,Aprendizaje, Gamificación,Trabajo en Equipo",
	  category: "other",
	},
	{
	  id:"5",
	  date: "2023",
	  route: "https://innovacioneducativa.upm.es/mooc/informacion-mooc?idmooc=356",
	  title: "Utilización de escape rooms y videojuegos educativos en la Educación Universitaria",
	  center: "E.T.S DE ING. DE SISTEMAS INFORMÁTICOS",
	  description: "",
	  tags: "Aprendizaje Activo,Aprendizaje Autónomo,Investigación educativa,Aula Invertida,Gamificación",
	  category: "ind",
	},
  ];
  